<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LabWatch.Core\LabWatch.Core.csproj" />
    <ProjectReference Include="..\LabWatch.Infrastructure\LabWatch.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>7b58b2ab-12e6-4ff7-a669-d42624ff259f</UserSecretsId>
  </PropertyGroup>

</Project>
